### ISSUE TITLE
estimateGas returns error

### ISSUE THREAD

**Issue by the-sea-ink** [BlockCertsSmartContract/cert-issuer#12]
![Screenshot_2020-01-27_15-49-49](https://user-images.githubusercontent.com/52105361/73185460-648ce100-411e-11ea-8581-fe1edf9acaba.png)
i would suggest to just use fixed gas limits for our transactions

**Comment by marcplustwo** [comment]
we should test if this still happens with different blockchain clients.

**Comment by marcplustwo** [comment]
Working now
