### ISSUE TITLE
adding fields to the contract with additional @context hosting 

### ISSUE THREAD

**Issue by flo-weiss** [BlockCertsSmartContract/cert-issuer#4]
ideally we can provide backwards compatibility applying this procedure. old certs are still valid and additional necessary information used within a modified schema can be used and checked via a hosted @context file. 

use example in: https://w3c.github.io/vc-data-model/

(for example could it be useful to add the "evidence" category to the cert.)

**Comment by marcplustwo** [comment]
I think for now we have figured this out. I hope.
